reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  auto_title_placeholder: "@coderabbitai"
  poem: false
  sequence_diagrams: true

chat:
  auto_reply: true

knowledge_base:
  learnings:
    scope: auto

language: en
early_access: false
